/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-items`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-navigation`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-item`; params?: Router.UnknownInputParams; } | { pathname: `/../data/history-list-data`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/data/history-list-data`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/history-items`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/history-navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/history-view`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/history/history-item`; params?: Router.UnknownOutputParams; } | { pathname: `/../data/history-list-data`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/data/history-list-data`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/hooks/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/../components/history/history-items${`?${string}` | `#${string}` | ''}` | `/../components/history/history-navigation${`?${string}` | `#${string}` | ''}` | `/../components/history/history-view${`?${string}` | `#${string}` | ''}` | `/../components/history/history-item${`?${string}` | `#${string}` | ''}` | `/../data/history-list-data${`?${string}` | `#${string}` | ''}` | `/../frontend/data/history-list-data${`?${string}` | `#${string}` | ''}` | `/../frontend/constants/Colors${`?${string}` | `#${string}` | ''}` | `/../frontend/hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../frontend/hooks/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../frontend/hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-items`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-navigation`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-view`; params?: Router.UnknownInputParams; } | { pathname: `/../components/history/history-item`; params?: Router.UnknownInputParams; } | { pathname: `/../data/history-list-data`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/data/history-list-data`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
